src/project/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using project.Data;
using project.Models;

namespace project.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ProductContext _context;

        public CategoriesController(ProductContext context)
        {
            _context = context;    
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.SingleOrDefaultAsync(m => m.ID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Admin");
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.SingleOrDefaultAsync(m => m.ID == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] Category category)
        {
            if (id != category.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Admin");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.SingleOrDefaultAsync(m => m.ID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.SingleOrDefaultAsync(m => m.ID == id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Admin");
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.ID == id);
        }
    }
}

src/project/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using project.Data;
using project.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.Net.Http.Headers;

namespace project.Controllers
{
    public class PhotosController : Controller
    {
        private readonly ProductContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public PhotosController(ProductContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Photos
        public async Task<IActionResult> Index()
        {
            var productContext = _context.Photos.Include(p => p.Product);
            return View(await productContext.ToListAsync());
        }

        // GET: Photos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos.SingleOrDefaultAsync(m => m.ID == id);
            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }

        // GET: Photos/Create
        public IActionResult Create()
        {
            ViewData["ProductID"] = new SelectList(_context.Products, "ID", "ID");
            return View();
        }

        // POST: Photos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ImgUrl,Name,ProductID")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                foreach (var Image in files)
                {
                    if (Image != null && Image.Length > 0)
                    {

                        var file = Image;
                        var uploads = Path.Combine(_hostingEnvironment.WebRootPath, "uploads\\img");

                        if (file.Length > 0)
                        {
                            var fileName = ContentDispositionHeaderValue.Parse
                                (file.ContentDisposition).FileName.Trim('"');

                            System.Console.WriteLine(fileName);
                            using (var fileStream = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                                photo.ImgUrl = file.FileName;
                            }
                        }
                    }
                }

                _context.Add(photo);
                await _context.SaveChangesAsync();
                return RedirectToAction("Edit","Products", new { id = photo.ProductID });
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ID", "ID", photo.ProductID);
            return View(photo);
        }

        // GET: Photos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos.SingleOrDefaultAsync(m => m.ID == id);
            if (photo == null)
            {
                return NotFound();
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ID", "ID", photo.ProductID);
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ImgUrl,Name,ProductID")] Photo photo)
        {
            if (id != photo.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var files = HttpContext.Request.Form.Files;
                    foreach (var Image in files)
                    {
                        if (Image != null && Image.Length > 0)
                        {

                            var file = Image;
                            var uploads = Path.Combine(_hostingEnvironment.WebRootPath, "uploads\\img");

                            if (file.Length > 0)
                            {
                                var fileName = ContentDispositionHeaderValue.Parse
                                    (file.ContentDisposition).FileName.Trim('"');

                                System.Console.WriteLine(fileName);
                                using (var fileStream = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create))
                                {
                                    await file.CopyToAsync(fileStream);
                                    photo.ImgUrl = file.FileName;
                                }
                            }
                        }
                    }

                    _context.Update(photo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhotoExists(photo.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Edit","Products", new { id = photo.ProductID });
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ID", "ID", photo.ProductID);
            return View(photo);
        }

        // GET: Photos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos.SingleOrDefaultAsync(m => m.ID == id);
            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var photo = await _context.Photos.SingleOrDefaultAsync(m => m.ID == id);
            _context.Photos.Remove(photo);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Admin");
        }

        private bool PhotoExists(int id)
        {
            return _context.Photos.Any(e => e.ID == id);
        }
    }
}

src/project/Views/Admin/Index.cshtml
@model IEnumerable<project.Models.Product>

@{
    IEnumerable<project.Models.Category> model2 = ViewBag.Categories;
    int categoryId = ViewBag.CategoryId;
}

@{
    ViewData["Title"] = "Admin";
}

<div class="bg-content">
    <div class="container-fluid">
        <div class="col-lg-2 col-md-4 col-sm-12 col-xs-12 categories-container">
            <div class="row categories-title-row text-center">Categories</div>
            <div class="row categories-row">
                <a class="input-class form-control text-center categories-button" asp-controller="Categories" asp-action="Create" style="height: auto;">Create New Category</a>
                <a asp-action="Index" asp-route-id="0" class="input-class form-control all-categories-button text-center">All</a>
                @foreach (var item2 in model2)
                {
                    <div class="input-class form-control category-button" style="height: auto;">
                        <div class="row text-center">
                            <a class="text-center" asp-action="Index" asp-route-id="@item2.ID">@Html.DisplayFor(modelItem => item2.Name)</a>
                        </div>
                        <div class="row text-center">
                            <a asp-controller="Categories" asp-action="Edit" asp-route-id="@item2.ID">Edit</a> |
                            <a asp-controller="Categories" asp-action="Delete" asp-route-id="@item2.ID">Delete</a> |
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="col-lg-10 col-md-8 col-sm-12 col-xs-12 products-container">
            <div class="row products-title-row text-center">Products</div>
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <a class="input-class form-control text-center new-product-button" asp-controller="Products" asp-action="Create" style="height: auto;">Create New Product</a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <a class="input-class form-control text-center new-product-button" asp-controller="Photos" asp-action="Index" asp-route-id="0" style="height: auto;">All Photos</a>
                </div>
            </div>
            <div class="row products-row">
                <div class="row product-row-title">
                    <div class="col-lg-1 col-md-2 col-sm-3 col-xs-2">
                        @Html.DisplayNameFor(model => model.ID)
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                        @Html.DisplayNameFor(model => model.Name)
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-3 col-xs-3">
                        @Html.DisplayNameFor(model => model.Price)
                    </div>
                    <div class="col-lg-5 col-md-3 col-sm-3 col-xs-3 photos-text-mobile">
                        @Html.DisplayNameFor(model => model.Photos)
                    </div>
                </div>

                @foreach (var item in Model)
                {
                    if (categoryId == item.CategoryID || categoryId == 0)
                    {
                        <div class="row product-row-list">
                            <div class="col-lg-1 col-md-2 col-sm-3 col-xs-2 row-id">
                                @Html.DisplayFor(modelItem => item.ID)
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-3 col-xs-4 row-name">
                                @Html.DisplayFor(modelItem => item.Name)
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-3 col-xs-3 row-price">
                                @Html.DisplayFor(modelItem => item.Price)
                            </div>
                            <div class="col-lg-5 col-md-6 col-sm-5 col-xs-3 row-photos-desktop">
                                @if (item.Photos.FirstOrDefault() != null)
                                {
                                    <div class="row photo-row-title">
                                        <div class="col-lg-3 col-md-3 col-sm-3">
                                            Name
                                        </div>
                                        <div class="col-lg-4 col-md-3 col-sm-3">
                                            ImgUrl
                                        </div>
                                    </div>
                                }

                                @foreach (var photo in item.Photos)
                                {
                                    <div class="row photo-row-list">
                                        <div class="col-lg-3 col-md-3 col-sm-3">
                                            @Html.DisplayFor(modelItem => photo.Name)
                                        </div>
                                        <div class="col-lg-4 col-md-3 col-sm-3">
                                            @Html.DisplayFor(modelItem => photo.ImgUrl)
                                        </div>
                                        <div class="col-lg-5 col-md-6 col-sm-6">
                                            <a asp-controller="Photos" asp-action="Edit" asp-route-id="@photo.ID">Edit</a> |
                                            <a asp-controller="Photos" asp-action="Delete" asp-route-id="@photo.ID">Delete</a>
                                        </div>
                                    </div>
                                }
                            </div>
                            <div class="col-md-2 col-sm-2 col-xs-3 row-photos-mobile">
                                <a asp-controller="Photos" asp-action="Index" asp-route-id="@item.ID">Photos</a>
                            </div>
                            <div class="col-lg-2 col-md-4 col-sm-6 col-xs-12">
                                <a asp-controller="Products" asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                                <a asp-controller="Products" asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>